2025-01-23 15:57:26,622 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\User\OneDrive\Документы\Homework\tests_12_4.py", line 38, in test_run
    runner_ = rat.Runner(True)
              ^^^^^^^^^^^^^^^^
  File "C:\User\OneDrive\Документы\Homework\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано bool
2025-01-23 15:57:26,623 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\User\OneDrive\Документы\Homework\tests_12_4.py", line 20, in test_walk
    walker = rat.Runner('walker', -1)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\User\OneDrive\Документы\Homework\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -1
